### PR TITLE
Fix Rails 5 deprecation warning for to_prepare

### LINKED ISSUE #169: Deprecation Warning: to_prepare
I'm using the latest version of Rails 5 beta 3 and am receiving this error:

```ruby
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use 
ActiveSupport::Reloader.to_prepare instead). (called from <class:Engine> at 
/Users/USER/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/devise_security_extension-
0.10.0/lib/devise_security_extension/rails.rb:7)
```

I'm on version 0.10.0 of the gem.

### PR DESCRIPTION
**Pull request by holidayworking**
Fixes #169

### CODE REVIEW

File: lib/devise_security_extension/rails.rb [hunk 1]
```diff
@@ -3,10 +3,15 @@ class Engine < ::Rails::Engine
...
-    ActionDispatch::Callbacks.to_prepare do
-      DeviseSecurityExtension::Patches.apply
-    end
 
+    if defined?(ActiveSupport::Reloader)
+      ActiveSupport::Callbacks.to_prepare do
+        DeviseSecurityExtension::Patches.apply
+      end
+    else
+      ActionDispatch::Callbacks.to_prepare do
```
Comment (tom-lord) [inline lib/devise_security_extension/rails.rb]: The warning I get is:

> DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead)

So, should this line instead be `ActiveSupport::Reloader.to_prepare do ...` ?
